name: Deploy to Private Server

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to private server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Ensure the directory exists and set the correct permissions
            mkdir -p /home/ubuntu/jukebox/database
            chown -R 1001:1001 /home/ubuntu/jukebox/database
            chmod -R 777 /home/ubuntu/jukebox/database
            
            # Login to GitHub Container Registry
            echo ${{ secrets.REGISTRY_TOKEN }} | docker login ghcr.io -u thomas-heniart --password-stdin
            
            # Pull the latest image
            docker pull ghcr.io/thomas-heniart/jukebox:${{ github.sha }}
            
            # Stop the existing container (if running)
            docker stop jukebox || true
            docker rm jukebox || true
            
            # Start the new container with .env file mounted
            docker run -d \
              --name jukebox \
              --restart unless-stopped \
              --user 1001:1001 \
              -p 3001:3000 \
              -v /home/ubuntu/jukebox/.env:/app/.env:ro \
              -v /home/ubuntu/jukebox/database:/app/database \
              ghcr.io/thomas-heniart/jukebox:${{ github.sha }}
